### PR TITLE
need files for packaging

### PR DESCRIPTION
**Pull request by illume**
We need the cli thing for a few reasons:

- shows user an error message (code to be replaced with an SDL2 function)
- allows changing data directories (when code and data are separated on Debian)
- the data/....txt file is needed so the data folder is packaged whilst we have no data in there.

### CODE REVIEW

**Comment by Bottersnike** [comment]
* Showing user error messages is handled by run_game.py
* That can be configured without that hellish bulk of code. Also, do you reasonably assume that in 4 days we can push a package to be debian repos?
* Did you even _see_ the `.gitkeep` file?? `.gitkeep` exists for a reason.

**Comment by illume** [comment]
The issue is with the setuptools not git with the data file.
I added the .gitkeep file.
Not all systems have tcl-tk, that is why the other code uses other variations. Mostly that cli.py code can be ignored.
Debian packaging will come after the compo.

**Comment by Bottersnike** [comment]
I'm looking at the cli.py file, and it doesn't seem to do _anything_ really worthwhile except define some globals and bootstrap the script.

**Comment by illume** [comment]
It's just some stuff for making it nicer for users.
Telling them about python versions, missing dependencies. Setting the right folder.
Showing the user there was an error.
A place to making sure threads are finished, ctrl c handling.

**Comment by Bottersnike** [comment]
We can handle all those without that mess of a file though. Asset loading is easy to just load relative to `__file__`, errors are already handled, and Ctrl+C handling just needs a case in `Game.mainloop()` that catches `KeyboardInterrupt` and then sets `Game.running = False`

**Comment by illume** [comment]
How about we leave this stuff there, and move onto making the game?

I've given reasons why I need the code. I'm open to cleanups of course :) But let's do those in a separate PR. So we have the base code ready to be used.

**Comment by Bottersnike** [comment]
Add back `cli.py` then, but don't just revert the two commits. No need to add the file in `data/` as I have a commit waiting on those 4 CIs (yes, it's a +11-1 commit waiting on 4 CIs)

**Comment by Bottersnike** [comment]
No. Don't do that. That's silly.

**Pull request merged**
