### PR TITLE
Fixes from pylint

### PR DESCRIPTION
**Pull request by MyreMylar**
Investigating [this issue here](https://github.com/pygame/pygame/issues/728), I thought I'd start by clearing the pylint output of as much as I could.

The current pylint (with -fixme disabled) output of stunt cat under 2.0.0.dev8 with this change list is:

    ************* Module stuntcat.cli
    stuntcat\cli.py:22:4: W0603: Using the global statement (global-statement)
    stuntcat\cli.py:26:8: C0415: Import outside toplevel (stuntcat) (import-outside-toplevel)
    stuntcat\cli.py:30:40: E1101: Instance of 'list' has no '_path' member (no-member)
    stuntcat\cli.py:30:40: W0212: Access to a protected member _path of a client class (protected-access)
    stuntcat\cli.py:57:12: C0415: Import outside toplevel (main) (import-outside-toplevel)
    stuntcat\cli.py:59:12: C0415: Import outside toplevel (stuntcat.main) (import-outside-toplevel)
    stuntcat\cli.py:60:8: C0415: Import outside toplevel (pygame) (import-outside-toplevel)
    stuntcat\cli.py:97:8: C0415: Import outside toplevel (pygame) (import-outside-toplevel)
    stuntcat\cli.py:137:4: C0415: Import outside toplevel (tkinter.messagebox) (import-outside-toplevel)
    stuntcat\cli.py:143:4: C0415: Import outside toplevel (pygame) (import-outside-toplevel)
    stuntcat\cli.py:145:8: E1101: Module 'pygame' has no 'quit' member (no-member)
    stuntcat\cli.py:166:19: E1101: Module 'pygame' has no 'K_ESCAPE' member (no-member)
    stuntcat\cli.py:166:32: E1101: Module 'pygame' has no 'K_SPACE' member (no-member)
    stuntcat\cli.py:166:44: E1101: Module 'pygame' has no 'K_RETURN' member (no-member)
    stuntcat\cli.py:166:57: E1101: Module 'pygame' has no 'K_KP_ENTER' member (no-member)
    stuntcat\cli.py:169:29: E1101: Module 'pygame' has no 'QUIT' member (no-member)
    stuntcat\cli.py:170:35: E1101: Module 'pygame' has no 'KEYDOWN' member (no-member)
    stuntcat\cli.py:171:35: E1101: Module 'pygame' has no 'MOUSEBUTTONDOWN' member (no-member)
    stuntcat\cli.py:173:8: E1101: Module 'pygame' has no 'quit' member (no-member)
    stuntcat\cli.py:174:11: E1101: Module 'pygame' has no 'error' member (no-member)
    ************* Module stuntcat.game
    stuntcat\game.py:28:8: E1101: Module 'pygame' has no 'init' member (no-member)
    stuntcat\game.py:95:29: E1101: Module 'pygame' has no 'QUIT' member (no-member)
    stuntcat\game.py:119:8: E1101: Module 'pygame' has no 'quit' member (no-member)
    ************* Module stuntcat.gifmaker
    stuntcat\gifmaker.py:141:29: E1101: Module 'pygame' has no 'KEYDOWN' member (no-member)
    stuntcat\gifmaker.py:141:57: E1101: Module 'pygame' has no 'K_g' member (no-member)
    ************* Module stuntcat.resources
    stuntcat\resources.py:66:4: W0603: Using the global statement (global-statement)
    stuntcat\resources.py:89:4: W0603: Using the global statement (global-statement)
    ************* Module stuntcat.scenes.cat3
    stuntcat\scenes\cat3.py:1:0: C0302: Too many lines in module (1032/1000) (too-many-lines)
    stuntcat\scenes\cat3.py:49:0: R0902: Too many instance attributes (14/7) (too-many-instance-attributes)
    stuntcat\scenes\cat3.py:88:4: W0221: Parameters differ from overridden 'update' method (arguments-differ)
    stuntcat\scenes\cat3.py:240:0: R0902: Too many instance attributes (20/7) (too-many-instance-attributes)
    stuntcat\scenes\cat3.py:288:4: W0221: Parameters differ from overridden 'update' method (arguments-differ)
    stuntcat\scenes\cat3.py:288:4: R0912: Too many branches (13/12) (too-many-branches)
    stuntcat\scenes\cat3.py:466:0: R0902: Too many instance attributes (8/7) (too-many-instance-attributes)
    stuntcat\scenes\cat3.py:490:4: W0221: Parameters differ from overridden 'update' method (arguments-differ)
    stuntcat\scenes\cat3.py:536:24: I1101: Module 'pygame.math' has no 'Vector2' member, but source is unavailable. Consider adding this module to extension-pkg-whitelist if you want to perform analysis based on run-time introspection of l
    iving objects. (c-extension-no-member)
    stuntcat\scenes\cat3.py:541:4: W0221: Parameters differ from overridden 'update' method (arguments-differ)
    stuntcat\scenes\cat3.py:559:24: I1101: Module 'pygame.math' has no 'Vector2' member, but source is unavailable. Consider adding this module to extension-pkg-whitelist if you want to perform analysis based on run-time introspection of l
    iving objects. (c-extension-no-member)
    stuntcat\scenes\cat3.py:564:4: W0221: Parameters differ from overridden 'update' method (arguments-differ)
    stuntcat\scenes\cat3.py:590:4: W0221: Parameters differ from overridden 'update' method (arguments-differ)
    stuntcat\scenes\cat3.py:622:0: R0902: Too many instance attributes (31/7) (too-many-instance-attributes)
    stuntcat\scenes\cat3.py:857:4: R0912: Too many branches (25/12) (too-many-branches)
    stuntcat\scenes\cat3.py:857:4: R0915: Too many statements (74/50) (too-many-statements)
    stuntcat\scenes\cat3.py:1007:28: E1101: Module 'pygame' has no 'KEYDOWN' member (no-member)
    stuntcat\scenes\cat3.py:1008:31: E1101: Module 'pygame' has no 'K_RIGHT' member (no-member)
    stuntcat\scenes\cat3.py:1012:33: E1101: Module 'pygame' has no 'K_LEFT' member (no-member)
    stuntcat\scenes\cat3.py:1016:33: E1101: Module 'pygame' has no 'K_a' member (no-member)
    stuntcat\scenes\cat3.py:1018:33: E1101: Module 'pygame' has no 'K_d' member (no-member)
    stuntcat\scenes\cat3.py:1020:33: E1101: Module 'pygame' has no 'K_UP' member (no-member)
    stuntcat\scenes\cat3.py:1025:30: E1101: Module 'pygame' has no 'KEYUP' member (no-member)
    stuntcat\scenes\cat3.py:1026:31: E1101: Module 'pygame' has no 'K_UP' member (no-member)
    stuntcat\scenes\cat3.py:1029:33: E1101: Module 'pygame' has no 'K_RIGHT' member (no-member)
    stuntcat\scenes\cat3.py:1031:33: E1101: Module 'pygame' has no 'K_LEFT' member (no-member)
    ************* Module stuntcat.scenes.loading
    stuntcat\scenes\loading.py:58:28: E1101: Module 'pygame' has no 'KEYDOWN' member (no-member)
    ************* Module stuntcat.scenes.platformer.event_handling
    stuntcat\scenes\platformer\event_handling.py:12:0: R0903: Too few public methods (1/2) (too-few-public-methods)
    stuntcat\scenes\platformer\event_handling.py:186:28: E1101: Module 'pygame' has no 'JOYHATMOTION' member (no-member)
    stuntcat\scenes\platformer\event_handling.py:211:28: E1101: Module 'pygame' has no 'JOYAXISMOTION' member (no-member)
    stuntcat\scenes\platformer\event_handling.py:241:8: E1101: Module 'pygame' has no 'K_UP' member (no-member)
    stuntcat\scenes\platformer\event_handling.py:242:8: E1101: Module 'pygame' has no 'K_DOWN' member (no-member)
    stuntcat\scenes\platformer\event_handling.py:243:8: E1101: Module 'pygame' has no 'K_LEFT' member (no-member)
    stuntcat\scenes\platformer\event_handling.py:244:8: E1101: Module 'pygame' has no 'K_RIGHT' member (no-member)
    stuntcat\scenes\platformer\event_handling.py:245:8: E1101: Module 'pygame' has no 'K_RSHIFT' member (no-member)
    stuntcat\scenes\platformer\event_handling.py:246:8: E1101: Module 'pygame' has no 'K_LSHIFT' member (no-member)
    stuntcat\scenes\platformer\event_handling.py:247:8: E1101: Module 'pygame' has no 'K_ESCAPE' member (no-member)
    stuntcat\scenes\platformer\event_handling.py:248:8: E1101: Module 'pygame' has no 'K_SPACE' member (no-member)
    stuntcat\scenes\platformer\event_handling.py:258:35: E1101: Module 'pygame' has no 'KEYDOWN' member (no-member)
    stuntcat\scenes\platformer\event_handling.py:259:36: E1101: Module 'pygame' has no 'KEYUP' member (no-member)
    ************* Module stuntcat.scenes.platformer.model
    stuntcat\scenes\platformer\model.py:8:0: R0903: Too few public methods (1/2) (too-few-public-methods)
    ************* Module stuntcat.scenes.platformer.platformer
    stuntcat\scenes\platformer\platformer.py:40:0: R0902: Too many instance attributes (8/7) (too-many-instance-attributes)
    ************* Module stuntcat.scenes.platformer.sprite
    stuntcat\scenes\platformer\sprite.py:7:0: E0611: No name 'Rect' in module 'pygame.rect' (no-name-in-module)
    stuntcat\scenes\platformer\sprite.py:34:4: W0221: Parameters differ from overridden 'update' method (arguments-differ)
    ************* Module stuntcat.scenes.platformer.unicyclecat
    stuntcat\scenes\platformer\unicyclecat.py:19:0: R0902: Too many instance attributes (11/7) (too-many-instance-attributes)
    
    ------------------------------------------------------------------
    Your code has been rated at 8.30/10 (previous run: 8.36/10, -0.06)

Which seems to show the remaining issues pretty clearly. Looks like we need an __all__ for the pygame module/package to clear out about 80% of the remaining issues.

 I'll give that a try next.

### CODE REVIEW

**Comment by zai1208** [comment]
Isn’t it meant to be `pygame.events.whatever key pressed `

**Comment by MyreMylar** [comment]
> Isn’t it meant to be `pygame.events.whatever key pressed `

For the key code constants? They are at pygame. scope, or at pygame.constants.

**Comment by zai1208** [comment]
Oh I think so that was pygame 1.9.6

**Comment by illume** [comment]
wow, this is great :)

**Comment by MyreMylar** [comment]
OK, pylint output after this PR looks like this:

    ************* Module stuntcat.scenes.cat3
    stuntcat\scenes\cat3.py:53:0: R0902: Too many instance attributes (15/12) (too-many-instance-attributes)
    stuntcat\scenes\cat3.py:395:0: R0902: Too many instance attributes (25/12) (too-many-instance-attributes)
    
    ------------------------------------------------------------------
    Your code has been rated at 9.99/10 (previous run: 9.99/10, -0.00)


I added a simple plyintrc file so you can now just run:

`pylint stuntcat`

To see the out put with some sensible defaults. Which are these:

    [MASTER]
    extension-pkg-whitelist=pygame
    
    [MESSAGES CONTROL]
    disable=fixme
    
    [DESIGN]
    max-attributes=12

I raised the max-attributes total because seven is an unreasonably small number for a pygame game - given that a sprite class like DirtySprite already uses six of them.

**Comment by MyreMylar** [comment]
Fairly sure those 2 new LGTM alerts are incorrect, but it might point to an issue with pygame.

**Comment by MightyJosip** [comment]
I think this is the problem with Rect not having __getitem__ defined in .pyi file. I have some time and today (or tomorrow) I will fix some things with type hints and then someone should rerun lgmt tests

**Comment by MyreMylar** [comment]
- Cleared out the two LGTM alerts that these changes generated previously. This project should now have 0 LGTM alerts after this PR.
- Switched the pylint configuration back to setup.cfg, but using the new style so that you can now just go `pylint stuntcat` to check the whole project with the current config. This is the same approach now used by pygame.

The final output from pylint with this PR still looks like this:

```
************* Module stuntcat.scenes.cat3
stuntcat\scenes\cat3.py:54:0: R0902: Too many instance attributes (15/12) (too-many-instance-attributes)
stuntcat\scenes\cat3.py:396:0: R0902: Too many instance attributes (25/12) (too-many-instance-attributes)

------------------------------------------------------------------
Your code has been rated at 9.99/10 (previous run: 9.99/10, +0.00)
```

Both are design issues with two of the classes in that file (`Shark` and `CatUniScene` ) which are both probably trying to do too much in a single class. I'm not going to tackle them in this PR, but hopefully reducing the number of issues down to these two makes the task a lot more manageable for anyone who wants to refactor (and lint) this game in the future.

**Comment by MyreMylar** [comment]
I should also say that I have tested the game (on Windows, with Python 3.8 and with pygame 2.0.0.dev10) and it still works.

**Comment by illume** [comment]
Very good!

I’ll have a look at merging this tonight when I’m back from the beach.

**Review by illume — APPROVED** [review]
Thanks for this. Sorry for the worlds slowest PR merge. I'm working today to merge the two open PRs here into main.

**Pull request merged**
